#!/usr/bin/env node
// Generated by `sidemux init`. Blocks inline test/lint/build so the agent
// delegates them to a tmux pane via the sidemux `run` MCP tool. Fail-open:
// any error or non-match exits 0 so it never bricks the Bash tool.
import { readFileSync } from 'node:fs';

function readStdin() {
  return new Promise((resolve) => {
    let data = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', (c) => (data += c));
    process.stdin.on('end', () => resolve(data));
    process.stdin.on('error', () => resolve(data));
  });
}

function matchesDelegated(commandLine, delegated) {
  const segments = commandLine.split(/&&|\|\||[;|]/).map((s) => s.trim()).filter(Boolean);
  for (const segment of segments) {
    for (const target of delegated) {
      if (segment === target || segment.startsWith(target + ' ')) return target;
    }
  }
  return null;
}

async function main() {
  if (process.env.SIDEMUX_DELEGATE_OFF === '1') process.exit(0);
  let payload;
  try {
    payload = JSON.parse((await readStdin()) || '{}');
  } catch {
    process.exit(0);
  }
  if (payload.tool_name && payload.tool_name !== 'Bash') process.exit(0);
  const commandLine = payload && payload.tool_input && payload.tool_input.command;
  if (typeof commandLine !== 'string') process.exit(0);

  let config;
  try {
    config = JSON.parse(readFileSync(new URL('./delegate.json', import.meta.url), 'utf8'));
  } catch {
    process.exit(0);
  }
  const commands = Array.isArray(config.commands) ? config.commands : [];
  const hit = matchesDelegated(commandLine, commands.map((c) => c.command));
  if (!hit) process.exit(0);

  const entry = commands.find((c) => c.command === hit) || {};
  const suggestion = entry.longRunning
    ? 'run { command: ' + JSON.stringify(hit) + ', description: "<why>", background: true }  (then wait { until: "pattern", … })'
    : 'run { command: ' + JSON.stringify(hit) + ', description: "<why>" }';
  process.stderr.write(
    '[sidemux] Delegate "' + hit + '" to a tmux pane instead of running it inline.\n' +
    'Use the sidemux MCP tool:\n  ' + suggestion + '\n' +
    'This keeps long output in the pane and your context lean. ' +
    '(Set SIDEMUX_DELEGATE_OFF=1 to bypass in an emergency.)\n',
  );
  process.exit(2);
}

main();
